const c=document.querySelector('canvas'),x=c.getContext('2d'),$=id=>document.getElementById(id);let W,H,last=0,color=localStorage.screenColor||'#36F76D',scene=localStorage.screenScene||'matrix',S={};const baseColors=['#36F76D','#35D7FF','#C77DFF','#FF4D7D','#FFB347'],title={matrix:'MATRIX FLOW',stars:'STARFIELD',fire:'FIREPLACE EMBER',rain:'RAIN ON GLASS',aurora:'AURORA',ink:'FLUID INK',dvd:'RETRO DVD',clock:'DIGITAL CLOCK',grid:'CYBER GRID',network:'PARTICLE NETWORK',terminal:'CODE TERMINAL'},chars='アァカサタナハマヤャラワン0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ$+-*/=%#&_(),.;:?!\\|{}<>[]^~';
const rgb=h=>{let n=parseInt(h.slice(1),16);return`${n>>16},${n>>8&255},${n&255}`},bg=a=>{x.fillStyle=`rgba(2,4,3,${a})`;x.fillRect(0,0,W,H)};
function reset(){let n=Math.max(20,W/+$('density').value|0);S={drop:Array.from({length:n},()=>Math.random()*-H/16),star:Array.from({length:260},()=>({x:(Math.random()-.5)*W,y:(Math.random()-.5)*H,z:Math.random()*W})),p:Array.from({length:160},()=>({x:Math.random()*W,y:Math.random()*H,vx:Math.random()-.5,vy:Math.random()-.5})),b:Array.from({length:9},()=>({x:Math.random()*W,y:Math.random()*H,r:100+Math.random()*200,vx:(Math.random()-.5)*.5,vy:(Math.random()-.5)*.5})),d:{x:W*.4,y:H*.4,vx:2,vy:1.5}}}
function matrix(k){bg(.08);let fs=+$('density').value;x.font=`${fs}px monospace`;x.textAlign='center';x.fillStyle=color;x.shadowColor=color;x.shadowBlur=8;S.drop.forEach((d,i)=>{x.fillText(chars[Math.random()*chars.length|0],i*W/S.drop.length+W/S.drop.length/2,d*fs);d+=k*(.6+Math.random());if(d*fs>H&&Math.random()>.975)d=-Math.random()*20;S.drop[i]=d});x.shadowBlur=0}
function stars(k){bg(.22);x.fillStyle=color;S.star.forEach(s=>{s.z-=k*9;if(s.z<1)Object.assign(s,{z:W,x:(Math.random()-.5)*W,y:(Math.random()-.5)*H});let X=s.x/s.z*W+W/2,Y=s.y/s.z*W+H/2;x.globalAlpha=1-s.z/W;x.fillRect(X,Y,Math.max(.5,(1-s.z/W)*3),Math.max(.5,(1-s.z/W)*3))});x.globalAlpha=1}
function fire(k){bg(.18);x.fillStyle=`rgba(${rgb(color)},.6)`;S.p.forEach(p=>{p.y-=k*(1+Math.random()*3);p.x+=Math.sin(p.y*.04)*k;if(p.y<-12){p.y=H+Math.random()*H*.1;p.x=Math.random()*W}x.beginPath();x.arc(p.x,p.y,1+Math.random()*2,0,7);x.fill()})}
function rain(k){bg(.15);x.strokeStyle=`rgba(${rgb(color)},.7)`;S.p.forEach(p=>{p.y+=k*15;p.x-=k*2;if(p.y>H){p.y=-30;p.x=Math.random()*W}x.beginPath();x.moveTo(p.x,p.y);x.lineTo(p.x-5,p.y+22);x.stroke()})}
function blobs(k,ink=false){bg(ink?.05:.14);S.b.forEach((b,i)=>{b.x+=b.vx*k*(ink?8:3);b.y+=b.vy*k*(ink?8:3);if(b.x<0||b.x>W)b.vx*=-1;if(b.y<0||b.y>H)b.vy*=-1;let g=x.createRadialGradient(b.x,b.y,0,b.x,b.y,b.r);g.addColorStop(0,`rgba(${rgb(color)},${ink?.05:.2})`);g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(b.x-b.r,b.y-b.r,b.r*2,b.r*2)})}
function dvd(k){bg(1);let d=S.d;d.x+=d.vx*k*2;d.y+=d.vy*k*2;if(d.x<0||d.x>W-145)d.vx*=-1;if(d.y<0||d.y>H-60)d.vy*=-1;x.strokeStyle=x.fillStyle=color;x.lineWidth=3;x.strokeRect(d.x,d.y,145,60);x.font='bold 28px sans-serif';x.textAlign='center';x.fillText('DVD',d.x+72,d.y+39)}
function clock(){bg(.15);let n=new Date();x.textAlign='center';x.fillStyle=color;x.shadowColor=color;x.shadowBlur=20;x.font=`${Math.min(W*.16,155)}px monospace`;x.fillText(n.toLocaleTimeString(),W/2,H/2);x.shadowBlur=0;x.fillStyle='#aab6ac';x.font='15px monospace';x.fillText(n.toDateString(),W/2,H/2+48)}
function grid(){bg(.18);x.strokeStyle=`rgba(${rgb(color)},.4)`;let h=H*.5;for(let i=-18;i<19;i++){x.beginPath();x.moveTo(W/2+i*W*.04,h);x.lineTo(W/2+i*W*.15,H);x.stroke()}for(let y=h;y<H;y+=(y-h)*.13+10){x.beginPath();x.moveTo(0,y);x.lineTo(W,y);x.stroke()}x.fillStyle=color;x.beginPath();x.arc(W/2,h,Math.min(W,H)*.12,Math.PI,0);x.fill()}
function network(k){bg(.14);let a=S.p;for(let p of a){p.x+=p.vx*k*2;p.y+=p.vy*k*2;if(p.x<0||p.x>W)p.vx*=-1;if(p.y<0||p.y>H)p.vy*=-1}for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){let dx=a[i].x-a[j].x,dy=a[i].y-a[j].y,q=dx*dx+dy*dy;if(q<15000){x.strokeStyle=`rgba(${rgb(color)},${.25*(1-q/15000)})`;x.beginPath();x.moveTo(a[i].x,a[i].y);x.lineTo(a[j].x,a[j].y);x.stroke()}}x.fillStyle=color;a.forEach(p=>x.fillRect(p.x,p.y,3,3))}
function terminal(){bg(.12);x.font='14px monospace';x.fillStyle=color;let l=['> boot sequence ... OK','packet transmitted: 0x5F3A','system status: ONLINE','accessing secure node_','[##########] 100%','root@network:~$ ./run'];for(let i=0;i<25;i++)x.fillText(l[i%6],30,(i*31+performance.now()*.04)%(H+30)-20)}
function loop(t){let k=Math.min(2.5,(t-last||16)/16)*+$('speed').value;last=t;({matrix,stars,fire,rain,aurora:()=>blobs(k),ink:()=>blobs(k,true),dvd,clock,grid,network,terminal}[scene])(k);requestAnimationFrame(loop)}
function setColor(v){if(!/^#[\da-f]{6}$/i.test(v))return;color=v.toUpperCase();$('colorPicker').value=$('colorText').value=color;document.documentElement.style.setProperty('--accent',color);document.documentElement.style.setProperty('--accent-rgb',rgb(color));localStorage.screenColor=color;document.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.color===color))}function pick(v){scene=v;$('scene').value=v;$('sceneTitle').textContent=title[v];localStorage.screenScene=v;reset()}function resize(){let d=Math.min(devicePixelRatio,2);W=innerWidth;H=innerHeight;c.width=W*d;c.height=H*d;x.setTransform(d,0,0,d,0,0);reset()}
$('colorPicker').oninput=e=>{$('randomColor').checked=false;localStorage.randomColor=false;setColor(e.target.value)};$('colorText').onchange=e=>{$('randomColor').checked=false;localStorage.randomColor=false;setColor(e.target.value)};$('scene').onchange=e=>pick(e.target.value);$('speed').oninput=()=>$('speedValue').textContent=`${+$('speed').value}×`;$('density').oninput=()=>{let n=+$('density').value;$('densityValue').textContent=n<19?'High':n>32?'Low':'Normal';reset()};$('randomColor').checked=localStorage.randomColor==='true';$('randomColor').onchange=e=>localStorage.randomColor=e.target.checked;document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{$('randomColor').checked=false;localStorage.randomColor=false;setColor(b.dataset.color)});$('toggle').onclick=e=>{let p=$('panel');p.classList.toggle('collapsed');e.target.textContent=p.classList.contains('collapsed')?'+':'−'};document.onkeydown=e=>{if(e.key==='h'||e.key==='H')document.body.classList.toggle('hidden-ui');if(e.key==='f'||e.key==='F')document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()};setInterval(()=>{if($('randomColor').checked){let a=baseColors.filter(v=>v!==color);setColor(a[Math.random()*a.length|0])}},12000);setColor(color);pick(scene);resize();onresize=resize;requestAnimationFrame(loop);
